"""users table

Revision ID: 3d0c88c5aa1e
Revises: 
Create Date: 2019-02-26 14:38:51.991432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d0c88c5aa1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('idx_16394_id_gejala', table_name='gejala_penyakit')
    op.drop_index('idx_16394_id_penyakit', table_name='gejala_penyakit')
    op.drop_table('gejala_penyakit')
    op.drop_table('menu')
    op.drop_index('idx_16400_id_penyakit', table_name='penyakit')
    op.drop_table('penyakit')
    op.drop_table('history')
    op.drop_index('idx_16388_id_gejala', table_name='gejala')
    op.drop_table('gejala')
    op.drop_table('gejala_input')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gejala_input',
    sa.Column('id_gejalainput', sa.INTEGER(), server_default=sa.text("nextval('gejalainput_id_gejalainput_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nama_gejala', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nama_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_gejalainput', name='gejala_input_pkey')
    )
    op.create_table('gejala',
    sa.Column('id_gejala', sa.BIGINT(), server_default=sa.text("nextval('gejala_id_gejala_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nama_gejala', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_gejala', name='idx_16388_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_16388_id_gejala', 'gejala', ['id_gejala'], unique=False)
    op.create_table('history',
    sa.Column('id_history', sa.INTEGER(), server_default=sa.text("nextval('history_id_history_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('input_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('output_sistem', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_history', name='history_pkey')
    )
    op.create_table('penyakit',
    sa.Column('id_penyakit', sa.BIGINT(), server_default=sa.text("nextval('penyakit_id_penyakit_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nama_penyakit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('definisi_penyakit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('penyebab_penyakit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pengobatan_penyakit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pencegahan_penyakit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('komplikasi_penyakit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_penyakit', name='idx_16400_primary'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_16400_id_penyakit', 'penyakit', ['id_penyakit'], unique=False)
    op.create_table('menu',
    sa.Column('id_menu', sa.INTEGER(), server_default=sa.text("nextval('menu_id_menu_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nama_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_menu', name='menu_pkey')
    )
    op.create_table('gejala_penyakit',
    sa.Column('id_gejala_penyakit', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_penyakit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_gejala', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bobot', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_gejala'], ['gejala.id_gejala'], name='gejala_penyakit_ibfk_1', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_penyakit'], ['penyakit.id_penyakit'], name='gejala_penyakit_ibfk_2', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_gejala_penyakit', name='idx_16394_primary')
    )
    op.create_index('idx_16394_id_penyakit', 'gejala_penyakit', ['id_penyakit'], unique=False)
    op.create_index('idx_16394_id_gejala', 'gejala_penyakit', ['id_gejala'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
